apiVersion: v1
kind: ConfigMap
metadata:
  name: bitwarden-config
  labels:
    app: bitwarden
data:
  SIGNUPS_ALLOWED: "false"
  INVITATIONS_ALLOWED: "true"
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "587"
  SMTP_SSL: "true"
